nav:
  - Home: index.md
  - Classes:
      - Peasant: ./classes/peasant.md
      - Monk: ./classes/monk.md
      - Priest: ./classes/priest.md
      - Rogue: ./classes/rogue.md
      - Warrior: ./classes/warrior.md
      - Wizard: ./classes/wizard.md
  - Equipment: ./equipment/
  - Lore: ./lore/
  - Hunting Grounds: ./hunting_grounds/
  - Mounts: mounts.md
  - Quests:
      - Quest List: ./quests/
      - Circles: ./quests/circles/
  - Professions: ./professions/
  - Religion: ./religion/
  - Towns: ./towns/
